version: 2
updates:
  # Required configurations
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '12:20'
      # Using my timezone
      timezone: 'NZ'
    open-pull-requests-limit: 10

    # Default configurations
    # Configs related to the actual PR
    assignees:
      - 'olesiaMartushkanova'
    reviewers:
      - 'olesiaMartushkanova'
