name: Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run tests
        working-directory: test/unit-tests
        run: yarn test:unit

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: Okirshen/npm-publisher@1.0.0
      - name: Publish to npm
        run: npm publish
