name: Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run tests
        working-directory: test/unit-tests
        run: yarn test:unit

      - name: Check coverage
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.TOKEN }}
          test-command: 'yarn jest --coverage'
